name: Validate Vehicle Profiles

on: [pull_request]

jobs:
  validate-vehicle-profiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          cd .vehicle_profiles
          npm ci
          npm run validate